AspNetCoreToDo/Models/ErrorViewModel.cs
namespace AspNetCoreToDo.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

AspNetCoreToDo/Models/ManageUsersViewModel.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Identity;

namespace AspNetCoreToDo.Models
{
    public class ManageUsersViewModel
    {
        public IdentityUser[] Administrators { get; set; }
        public IdentityUser[] Everyone { get; set; }
    }
}

AspNetCoreToDo/Models/ToDoItem.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace AspNetCoreToDo.Models
{
    public class ToDoItem
    {
        public Guid Id { get; set; }

        public bool IsDone { get; set; }
        public string? UserId { get; set; }

        [Required]
        public string Title { get; set; }

        public DateTimeOffset? DueAt { get; set; }

        
    }
}

AspNetCoreToDo/Models/ToDoViewModel.cs
namespace AspNetCoreToDo.Models
{
    public class ToDoViewModel
    {
        public IEnumerable<ToDoItem> Items { get; set; }
    }
}

AspNetCoreToDo/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using AspNetCoreToDo.Models;

namespace AspNetCoreToDo.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

AspNetCoreToDo/Controllers/ManageUsersController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using AspNetCoreToDo.Models;
using Microsoft.EntityFrameworkCore;

namespace AspNetCoreToDo.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class ManageUsersController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;

        public ManageUsersController(UserManager<IdentityUser> userManager)
        {
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            var admins = (await _userManager.GetUsersInRoleAsync("Administrator")).ToArray();
            var everyone = await _userManager.Users.ToArrayAsync();

            var model = new ManageUsersViewModel
            {
                Administrators = admins,
                Everyone = everyone
            };

            return View(model);
        }

        public async Task<IActionResult> DeleteUser(string id)
        {
            var user = await _userManager.FindByIdAsync(id);

            if (user != null)
            {
                var result = await _userManager.DeleteAsync(user);
                if (!result.Succeeded)
                {
                    var errors = string.Join(", ", result.Errors);
                    return RedirectToAction("Index", new { Id = id, Operation = "Delete", Status = "Failure", Message = errors });
                }
            }

            return RedirectToAction("Index");
        }


    }



}

AspNetCoreToDo/Controllers/ToDoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using AspNetCoreToDo.Models;
using AspNetCoreToDo.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;


namespace AspNetCoreToDo.Controllers
{
    [Authorize]
    public class ToDoController : Controller
    {
        private readonly IToDoItemService _toDoItemService;
        private readonly UserManager<IdentityUser> _userManager;

        public ToDoController(IToDoItemService toDoItemService, UserManager<IdentityUser> userManager)
        {
            _toDoItemService = toDoItemService;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            var currentUser = await _userManager.GetUserAsync(User);
            if (currentUser == null) return Challenge();

            var items = await _toDoItemService.GetIncompleteItemsAsync(currentUser);

            var model = new ToDoViewModel(){
                Items = items
            };

            return View(model);
        }

        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddItem(ToDoItem newItem)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("Index");
            }
            var currentUser = await _userManager.GetUserAsync(User);
            if (currentUser == null) return Challenge();
            var successful = await _toDoItemService.AddItemAsync(newItem, currentUser);

            if (!successful)
            {
                return BadRequest("Could not add item.");
            }

            return RedirectToAction("Index");
        }

        [ValidateAntiForgeryToken]
        public async Task<IActionResult> MarkDone(Guid id)
        {
            if (id == Guid.Empty)
            {
                return RedirectToAction("Index");
            }

            var currentUser = await _userManager.GetUserAsync(User);
            if (currentUser == null) return Challenge();
            var successful = await _toDoItemService.MarkDoneAsync(id, currentUser);

            if (!successful)
            {
                return BadRequest("Could not mark item as done.");
            }

            return RedirectToAction("Index");
        }
    }
}

AspNetCoreToDo/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

AspNetCoreToDo/Views/ManageUsers/Index.cshtml
@model ManageUsersViewModel

@{
    ViewBag.Title = "Manage Users";
}

<h2>@ViewBag.Title</h2>

<h3>Administrators</h3>

<table class="table">
    <tr>
        <th>Username</th>
        <th>Email</th>
        <th></th>
    </tr>
    @foreach (var user in Model.Administrators)
    {
        <tr>
            <td>@user.UserName</td>
            <td>@user.Email</td>
        </tr>
    }
</table>

<h3>Everyone</h3>

<table class="table">
    <tr>
        <th>Username</th>
        <th>Email</th>
        <th></th>
    </tr>
    @foreach (var user in Model.Everyone)
    {
        <tr>
            <td>@user.UserName</td>
            <td>@user.Email</td>
            <td>
                @if (user.UserName != User.Identity.Name)
                {
                    <a href="@Url.Action("DeleteUser", new { id = user.Id })">Delete</a>
                }
            </td>
        </tr>
    }

AspNetCoreToDo/Views/Shared/_AdminActionsPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using AspNetCoreToDo.Models

@inject SignInManager<IdentityUser> signInManager
@inject UserManager<IdentityUser> userManager

@if(signInManager.IsSignedIn(User))
{
    var currentUser = await userManager.GetUserAsync(User);

    var isAdmin = currentUser != null 
        && await userManager.IsInRoleAsync(currentUser, Constants.AdministratorRole);

    if(isAdmin){
        <ul class="nav navbar-nav navbar-right">
            <li>
                <a class="nav-link text-dark" asp-controller="ManageUsers" asp-action="Index">Manage Users</a>
                </li>
        </ul>
    }

}    

AspNetCoreToDo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AspNetCoreToDo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AspNetCoreToDo.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AspNetCoreToDo</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ToDo" asp-action="Index">Mi lista ToDo</a>
                        </li>
                    </ul>
                    <partial name="_AdminActionsPartial" />
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - AspNetCoreToDo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

AspNetCoreToDo/Views/ToDo/AddItemPartial.cshtml
@model ToDoItem

<form asp-action="AddItem" method="POST">
    <label asp-for="Title">Tarea</label>
    <input asp-for="Title"/>
    <label asp-for="DueAt">Fecha de vencimiento</label>
    <input asp-for="DueAt" type="date"/>
    <button type="submit" class="btn btn-primary">Agregar</button>
</form>

AspNetCoreToDo/Views/ToDo/Index.cshtml
@model ToDoViewModel
@using Humanizer

@{
    ViewData["Title"] = "Maneja tus tareas";
}

<div class="panel panel-default todo-panel">
    <div class="panel-heading">
        <h3 class="panel-title">@ViewData["Title"]</h3>
    </div>
    <table class="table table-hover">
        <thead>
            <tr>
                <td>&#x2714</td>
                <td>Item</td>
                <td>Due</td>
            </tr>
        </thead>


        @foreach (var item in Model.Items)
        {
            <tr>
                <td>
                    <form asp-action="MarkDone" method="POST">
                        <input type="hidden" name="id" value="@item.Id" />
                        <input type="checkbox" class="done-chekbox" asp-for="@item.IsDone" />
                    </form>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @item.DueAt.Humanize()
                </td>
            </tr>
        }
    </table>

    <div class="panel-footer add-item-form">
        @await Html.PartialAsync("AddItemPartial", new ToDoItem())
    </div>
</div>